FROM postgres:16.13

RUN apt-get update && apt-get install -y \
    postgresql-16-postgis-3 \
    postgresql-16-pgvector \
    && rm -rf /var/lib/apt/lists/*


COPY packages/database/migration/* /docker-entrypoint-initdb.d/

CMD ["postgres"]
